### ISSUE TITLE
PROXY_USER/PROXY_PASSWORD not used?

### ISSUE THREAD

**Issue by WolfRevo** [Raerten/rgosocks5#12]
Do I miss something?

```
services:
  socks5:
    image: raerten/rgosocks5
    ports:
      - "1080:1080" # socks5 port
    environment:
      - PROXY_USER=<my_proxy_user>
      - PROXY_PASSWORD=<nice_base32_pw>
      - DNS_HOST=<dns_ipv4>
      - DNS_PORT=<dns_port>
      - TZ=Europe/<my_timezone>
    networks:
      - <docker-network>
    dns:
      - <dns_ipv4>
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G

networks:
  <docker-network>:
    external: true
```
Runs up but proxy does not request user/pw and works without authentication (tested with firefox + telegram). 
If I try with user/pw I get the following error:
`ERROR server: failed to authenticate: no supported authentication mechanism`

Any help appreciated.
